spring:
  application:
    name: bettr-api
  main:
    banner-mode: log
    web-application-type: REACTIVE
  web:
    resources:
      add-mappings: false
  r2dbc:
    name: bettr
    url: r2dbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:bettr}
    username: ${PGUSER:bettr}
    password: ${PGPASSWORD:bettr}
    pool:
      initial-size: 5
      max-size: 15
      max-idle-time: 2m
      max-life-time: 30m
      validation-query: SELECT 1
    properties:
      preparedStatementCacheQueries: 0

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
  endpoints:
    web:
      base-path: /actuator/
      exposure:
        include: "*"
    prometheus:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

endpoints:
  prometheus:
    enabled: true

logging:
  level:
    root: INFO
    org.javamoney.moneta: WARN
  config: "classpath:${LOGGING_CONFIG_FILE:log4j2.xml}"
