[versions]
compiler-java = "17"
compiler-kotlin = "2.0"
kotlin = "2.0.21"
spring-boot = "3.5.6"
kotlinx-collections-immutable = "0.3.8"
kotlinx-coroutines = "1.10.1"
kotlinx-datetime = "0.6.1"
kotlinx-serialization-json = "1.8.0"
kotlin-logging = "7.0.3"
log4j = "2.24.3"
slf4j = "2.0.16"
micrometer = "1.14.3"
valiktor = "0.12.0"
javax-money-api = "1.1"
moneta = "1.4.4"

netty = "4.2.5.Final"
json-smart = "2.5.2"
kotest-core = "5.9.1"
kotest-spring = "1.3.0"
test-logger = "4.0.0"
jacoco-log = "3.1.0"
kotlinter = "4.4.1"
disruptor = "4.0.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
jacoco-log = { id = "org.barfuin.gradle.jacocolog", version.ref = "jacoco-log" }

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-core = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-log4j2 = { module = "org.springframework.boot:spring-boot-starter-log4j2" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }

valiktor-core = { module = "org.valiktor:valiktor-core", version.ref = "valiktor" }
valiktor-javatime = { module = "org.valiktor:valiktor-javatime", version.ref = "valiktor" }
valiktor-javamoney = { module = "org.valiktor:valiktor-javamoney", version.ref = "valiktor" }
valiktor-test = { module = "org.valiktor:valiktor-test", version.ref = "valiktor" }

javax-money-api = { module = "javax.money:money-api", version.ref = "javax-money-api" }
javax-money-moneta = { module = "org.javamoney:moneta", version.ref = "moneta" }

log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "log4j" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
netty-http2 = { module = "io.netty:netty-codec-http2", version.ref = "netty" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }

json-smart = { module = "net.minidev:json-smart", version.ref = "json-smart" }

kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest-core" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest-core" }
kotest-extensions-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version.ref = "kotest-spring" }

disruptor = { module = "com.lmax:disruptor", version.ref = "disruptor" }
